# Azure Devops pipeline file
name: $(Date:yyyyMMdd)-$(Rev:r)

trigger: none
pr: none

stages:
- stage: Build_Selz
  # condition: in(variables['build.sourceBranch'], 'refs/heads/master')
  jobs:
  - deployment: Deploy
    environment: development
    pool:
      vmImage: ubuntu-latest
    strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self
            - task: CmdLine@2
              inputs:
                script: |
                  npm install --save-dev webpack
                  npm run build:selz'